### ISSUE TITLE
[joss] Tests?

### ISSUE THREAD

**Issue by sneakers-the-rat** [juanmc2005/diart#156]
Hey! Sorry for the long delay. just started a new job and things have been hectic. 

Orienting myself to the package, and I can't seem to find any tests? JOSS doesn't have a minimum test coverage requirement or anything like that, but it does ask that essential functionality is tested, and I have interpreted that in the past as meaning unit tests that cover most of the major operations described in the docs and the paper. 

I'll tag all my issues from the review with [joss] and also link back to the review so we can track them from there

Part of:
https://github.com/openjournals/joss-reviews/issues/5266

**Comment by juanmc2005** [comment]
Hi @sneakers-the-rat ! Thanks for your feedback! I've been wanting to add unit tests for some time (#94).
I will prioritize it so they are implemented for the main features of the library.

Otherwise, the core operations of the library can also be verified using the CLI interface: `diart.stream` for the microphone and individual files, and `diart.benchmark` to reproduce the performance that we claim (e.g. on the AMI dataset).

**Comment by sneakers-the-rat** [comment]
I'd be happy to make a pull request adding some tests as examples, if you haven't written them before :)

**Comment by juanmc2005** [comment]
That would be awesome, thank you!

**Comment by sneakers-the-rat** [comment]
Here's an example test for the config:
https://github.com/sneakers-the-rat/diart/commit/b1a0ccaa35f8b36aa30f978a4bcb16db69652a42

after installing with `[tests]`, one can run `pytest` from the repo root to run the tests. Gave an example of using test fixtures for random value init to test that the inputs arent being ignored and defaults substituted

**Comment by sneakers-the-rat** [comment]
I offered to help with how to write tests! So am happy to answer questions/give examples here :)

**Comment by juanmc2005** [comment]
Test PR #237 has been merged and will be included in the next release (v0.10)
