### ISSUE TITLE
ImportError: cannot import name 'OnlineSpeakerDiarization' from 'diart'

### ISSUE THREAD

**Issue by ameer-kanaan** [juanmc2005/diart#220]
I am trying to run your tutorial on [transcription coloring](https://betterprogramming.pub/color-your-captions-streamlining-live-transcriptions-with-diart-and-openais-whisper-6203350234ef). But I am getting the mentioned error.

The library runs fine per "diart.stream microphone".

Running on Windows 11 with Python 3.11.5. I am on your .yml environment.

**Comment by thieugiactu** [comment]
They got rid of  OnlineSpeakerDiarization,  please use SpeakerDiarization and SpeakerDiarizationConfig instead.

**Comment by juanmc2005** [comment]
I just updated the gist accordingly

**Comment by juanmc2005** [comment]
@ameer-kanaan some people have reported this but it could be due to many things, so I can't help without more information.

I suggest you debug line by line to find out what's going on.

You can also take a look at:
- #203
- #161 
- [gist comments](https://gist.github.com/juanmc2005/ed6413e697e176cb36a149d8c40a3a5b) 

Some common problems are Whisper being too slow due to RAM and/or CPU requirements, and sample rate mismatch

**Comment by juanmc2005** [comment]
@ameer-kanaan ok, I'll try to take a look at this issue in the coming weeks to see if something broke the whisper code with v0.8
