### ISSUE TITLE
timestamp is not reset when diarizing a new audio stream

### ISSUE THREAD

**Issue by ywangwxd** [juanmc2005/diart#257]
How to reproduce:
1.  start the service, choose the SpeakerDiarization pipeline
2.  send audio streaming through websocket on the client side
3.  after finishing the first audio file, start the client again with a new audio file
4. check the output RTTM file, the timestamp of the RTTM result of the second audio file is not reset, it is counted based on the end time of the first audio.

**Comment by ywangwxd** [comment]
> Hey, i have found this to be true too. I don't believe the server is cleaning up the stream correctly. This also makes multiple client connections tough - since the server instance is tied to the `AudioSource` family of objects.

There is a workaround, you can create multipe instances of auido source with different port number and pipeline instances. In this way, it seems each websocket port is working independently.

But I am still confused about the muliple client connections within one websocket. From the timestamp, it looks like continuous clients connection will have continuous timesstamp, but I found the speaker labelling is not consistent. Here is how to reproduce what I said.
1. make sure you start the service with only one websocket port.
2.  use diart.client to send an audio file through websocket
3. after the above finished, send the same audio file through websocket
4. check the resulted RTTM file, the speaker labelling results are not consistent, for a simple audio, I found the first one was very accurate but latter was not.

**Comment by juanmc2005** [comment]
Hello! As Imentioned in #252, this is indeed a limitation of `WebSocketAudioSource`.
I think `StreamingInference` does clean the state automatically because the `AudioSource` changes between two runs.
However, in a `WebSocketAudioSource` the source remains the same, and there's this underlying assumption that the conversation keeps going until you kill the connection (also that all audio chunks are contiguous).

Concerning why the results are not the same in the second pass, this has a simple explanation. When you begin the second pass, the state actually remembers the end of the first pass, so depending on your latency, step and chunk duration, a certain duration from the end of the file is still used to process the beginning of the second pass **at the same time**. This can snowball over time.

I'd really like to get rid of these issues and improve the websocket implementation. I think @janaab11's PR is a nice starting point. Just waiting for you to change the target branch to the main repo instead of the fork, then we can build this feature over there.

**Comment by ywangwxd** [comment]
> Hello! As Imentioned in #252, this is indeed a limitation of `WebSocketAudioSource`. I think `StreamingInference` does clean the state automatically because the `AudioSource` changes between two runs. However, in a `WebSocketAudioSource` the source remains the same, and there's this underlying assumption that the conversation keeps going until you kill the connection (also that all audio chunks are contiguous).
> 
> Concerning why the results are not the same in the second pass, this has a simple explanation. When you begin the second pass, the state actually remembers the end of the first pass, so depending on your latency, step and chunk duration, a certain duration from the end of the file is still used to process the beginning of the second pass **at the same time**. This can snowball over time.
> 
> I'd really like to get rid of these issues and improve the websocket implementation. I think @janaab11's PR is a nice starting point. Just waiting for you to change the target branch to the main repo instead of the fork, then we can build this feature over there.

I got it, thank you.
